import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

type props = {
  children: React.ReactNode;
};

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "300", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Learning | Data fetching",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: props) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
